### ISSUE TITLE
Spatial embedding data and Node2vec hyperparameters

### ISSUE THREAD

**Issue by dan-grm** [wengwenchao123/RGDAN#1]
In Line 82 in `utils.py`, the spatial embedding, i.e., the Node2vec embedding, I suppose, is loaded from the directory `data/SE`.
However, this directory is not contained in the data folder.
Further, I cannot find any information about which hyperparameters have been used for Node2vec.
It would be nice for reproducibility if you could provide the Node2vec hyperparameters,
and perhaps additionally add the Node2vec embedding to the data directory.

Thank you!

**Comment by wengwenchao123** [comment]
> In Line 82 in `utils.py`, the spatial embedding, i.e., the Node2vec embedding, I suppose, is loaded from the directory `data/SE`. However, this directory is not contained in the data folder. Further, I cannot find any information about which hyperparameters have been used for Node2vec. It would be nice for reproducibility if you could provide the Node2vec hyperparameters, and perhaps additionally add the Node2vec embedding to the data directory.
> 
> Thank you!

Thank you for your interest in this work. I am sorry that I did not find that I did not upload the SE file, maybe because there was a problem on the website at that time. I have now uploaded the relevant files to the data directory. As for the code of Node2vec you mentioned, I didn't keep it because the previous code was damaged. Now I only have the version borrowed from others a long time ago, and I can't use it directly. Please give me some time to debug the code before uploading it.

**Comment by wengwenchao123** [comment]
> In Line 82 in `utils.py`, the spatial embedding, i.e., the Node2vec embedding, I suppose, is loaded from the directory `data/SE`. However, this directory is not contained in the data folder. Further, I cannot find any information about which hyperparameters have been used for Node2vec. It would be nice for reproducibility if you could provide the Node2vec hyperparameters, and perhaps additionally add the Node2vec embedding to the data directory.
> 
> Thank you!
Hello, I have found and debugged the code of Node2vec, you can find it in the newly uploaded file

**Comment by wengwenchao123** [comment]
You're welcome to ask me any more questions

**Comment by dan-grm** [comment]
First of all, thank you for your quick reply!
One more question came to my mind when looking at the code in `generateSE.py`:
There you read the adj. matrix of the BJ500 dataset.
Does that mean that you used these Node2vec params (p=2, q=1, etc.) only for this dataset,
or did you use the same parameters for all datasets?
I am also interested how you found these hyperparameters?

Thanks in advance!

**Comment by wengwenchao123** [comment]
In this context, I used Node2vec to generate the SE file only for BJ500, while the other two SE files were obtained from GMAN, and they were also generated using Node2vec.

Regarding hyperparameters, since I borrowed the usage of Node2vec from elsewhere, I did not make any modifications to the hyperparameters. However, I conducted an experiment earlier where I generated a new SE file using the adjacency matrix of the METR dataset and trained the model with it. I found that the final performance did not show significant differences. Therefore, I believe that this may not have a substantial impact on the ultimate results.
